// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/flags.ts";
import * as $$$1 from "./loaders/icons.ts";

const manifest = {
  "loaders": {
    "stoneco/loaders/flags.ts": $$$0,
    "stoneco/loaders/icons.ts": $$$1,
  },
  "name": "stoneco",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
